env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier # Make sure "prettier" is the last element in this list.
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - prettier-plugin-tailwindcss
rules: {}
settings:
  react:
    version: "detect"
